[window]
padding.x = 20
padding.y = 20

[font]
normal.family = "Iosevka Nerd Font"
size = 14
glyph_offset.x = 0
glyph_offset.y = 0

[colors]
primary.background = "#0e0a02"
primary.foreground = "#bfc9db"
cursor.text = "CellForeground"
cursor.cursor = "#bfc9db"

[colors.normal]
black = "#646a73"
blue = "#8AB4F8"
cyan = "#03dac6"
green = "#a5d6a7"
magenta = "#bb86fc"
red = "#cf6679"
white = "#ffffff"
yellow = "#fff59d"

[colors.bright]
black = "#646a73"
blue = "#8AB4F8"
cyan = "#03dac6"
green = "#a5d6a7"
magenta = "#bb86fc"
red = "#cf6679"
white = "#858893"
yellow = "#ffecb3"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
