import = ["/home/tux/.config/alacritty/colors.toml", "/home/tux/.config/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[window]
dynamic_title = true
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 23

[window.padding]
x = 15
y = 15
