import = ["~/.config/alacritty/colors.toml"]

live_config_reload = false

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.bold]
family = "Terminess Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Terminess Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Terminess Nerd Font"
style = "Italic"

[font.normal]
family = "Terminess Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 1

[window.padding]
x = 20
y = 20
