live_config_reload = true

[[colors.indexed_colors]]
color = "0xf78c6c"
index = 16

[[colors.indexed_colors]]
color = "0xff5370"
index = 17

[[colors.indexed_colors]]
color = "0x303030"
index = 18

[[colors.indexed_colors]]
color = "0x353535"
index = 19

[[colors.indexed_colors]]
color = "0xb2ccd6"
index = 20

[[colors.indexed_colors]]
color = "0xeeffff"
index = 21

[colors.bright]
black = "#464c5b"
blue = "#67bbff"
cyan = "#93cee9"
green = "#98dd8b"
magenta = "#a385dc"
red = "#e06c75"
white = "0xeeffff"
yellow = "#ecd3a0"

[colors.cursor]
cursor = "0xeeffff"
text = "0x212121"

[colors.normal]
black = "#14171c"
blue = "#67bbff"
cyan = "#93cee9"
green = "#98dd8b"
magenta = "#a385dc"
red = "#fd6b85"
white = "#97a4a0"
yellow = "#ecd3a0"

[colors.primary]
# background = "#14171c"
#background = "#21242c"
background = "#282828"
foreground = "#a2b5ce"

[env]
TERM = "alacritty"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[window]
opacity = 1.0

[window.padding]
x = 25
y = 25
